### ISSUE TITLE
Delivery Service application - Failure to launch service - CrashLoopBackOff

### ISSUE THREAD

**Issue by abymsft** [mspnp/aks-fabrikam-dronedelivery#21]
Hi Team,

On step 9 workload [deploy ](https://github.com/customer-org-sandbox/aks-fabrikam-dronedelivery/blob/main/09-workload.md)

I am unable to get the Delivery service to work. Please check the screen shots below

**get pods output**
![image](https://user-images.githubusercontent.com/50873759/151260586-095b3cfa-e81e-4e08-b5f5-dbaf6b085d5c.png)
**describe pod output**
![image](https://user-images.githubusercontent.com/50873759/151260766-c02cf6fd-1c95-41cb-993f-7c50dcbd727d.png)

Is anyone else facing this issue?
P.S: I changed the image repo URLs from public (docker) to private acr repos.

**Comment by MinhTienTH** [comment]
Hi. Have you solved this issue?
