### ISSUE TITLE
Version changes in order to deploy AKS, Flux & AGIC

### ISSUE THREAD

**Issue by samseth** [mspnp/aks-fabrikam-dronedelivery#23]
I am using latest version of AKS 1.24

I had to change "apiVersion" for ClusterRole and ClusterRoleBinding to "rbac.authorization.k8s.io/v1" , in flux.yaml, in order to deploy flux in step 6 : GitOps.

aadpodidentity related CRDs were missing so  I ran: 
kubectl create -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml

I had to change --version parameter to latest i.e. 1.5.2 in order to install AGIC helm package in Step 8 : Ingress Controller

In Step 9: Workload , while installing workload helm packages, I am seeing following error: 

no matches found: ingress.hosts[0].name=dronedelivery.fabrikam.com

**Comment by salils3211** [comment]
Hi ,

I am facing the similar issues when ASK version 1.24  / later is used. Please update this code to rectify this issue
